data_ingestion_config:
  zip_file_name: dataset.zip
  bucket_name: sign-recognition

data_transformation_config:
  img_size: 224
  degree_n: 5
  degree_p: 5
  train_ratio: 0.7
  valid_ratio: 0.2
  std: [0.5]
  mean: [0.5]

model_trainer_config:
  epochs: 15
  lr: 0.001
  batch_size: 8
  num_workers: 2

model_evaluation_config:
  batch_size: 16
  num_workers: 2
  bucket_name: sign-recognition

model_pusher_config:
  bucket_name: sign-recognition

prediction_pipeline_config:
  input_image: input.jpg
  bucket_name: sign-recognition
  model_name: model.pt
  threshold: 0.3